---
title: "R Markdown Practice"
author: "R. Burke Squires"
date: "May 2024"
output:
  xaringan::moon_reader:
    css: mckpam.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
 
---

# Analysis

- Open `4-1-Practice-Start-here.Rmd`

- This is taken from `The Carpentries` [`R for Reproducible Scientific Analysis`](https://swcarpentry.github.io/r-novice-gapminder/) repository.

- This project uses the `Gapminder` data set for some simple analysis

- The [Gapminder project](https://www.gapminder.org/data/) has collected data from countries around the world that look at communication, economic, education, environment, health, infrastructure, population, society, and work in each country.


---

# Practice

- We will take a mock analysis and create a different outputs for it.

- We will build the following:

  - R notebook
  - HTML document
  - Presentation
  - RShiny app
  - Dashboard (if there is time)

---

# Output

- Notebooks
-	Documents
- Presentations
- Interactive Documents
- Dashboards
- Other
  - Websites
  - Blogs
  - Books

---

# R Notebook

-	Create simple analysis of Gapminder data using:
  - Creating a new R Notebook first using:
    - `File` -> `New File…` -> `R Notebook`
  - Preview the notebook
  - Erase everything in the template
  - Copy and paste in our markdown introduction
  - Add code chunks


---

# Document (HTML)

  -	Creating a new R Markdown document using:
    -	`File` -> `New File…` -> `R Markdown`
  -	Look at the `Document` menu options
    - `HTML` -> `OK`
  -	Knit the template to see what it should produce
  -	Erase everything in the template, and type it in for practice as shown on screen
  -	Add your text and a graph or two from the analysis notebook
  -	Advanced
    -	Try repeating with PDF or Word as the output

---

# Break

---

# Presentation (Slides)

-	Creating a new R Markdown document using:
  - `File` -> `New File…` -> `R Markdown`
-	Look at the `Presentation` menu options
  -	`HTML (ioslides)` -> `OK`
-	Knit the template to see what it should produce
-	Erase everything in the template, and type it in for practice as shown on screen
-	Add your text and a graph or two from the analysis notebook
-	Advanced
  -	Try repeating with HTML (Slidy), PDF (Beamer), or PowerPoint as the output

---

# RShiny app

-	Creating a new R Markdown document using:
  - `File` -> `New File…` -> `R Markdown`
-	Look at the `Shiny` menu options
  -	`Shiny Document` -> `OK`
-	Knit the template to see what it should produce
-	Erase everything in the template, and type it in for practice as shown on screen
  - Add your text and a graph or two from the analysis notebook
-	Advanced
  - Try repeating with `Shiny Presentation` as the output

---

# Dashboard

-	Creating a new R Markdown document using:
  - `File` -> `New File…` -> `R Markdown`
-	Look at the `From Template` menu options
  - `Flex Dashboard` -> `OK`
-	Knit the template to see what it should produce
-	Erase everything in the template, and type it in for practice as shown on screen
  - Add your text and a graph or two from the analysis notebook

---

# Q & A

