---
title: "R Markdown Practice"
author: "R. Burke Squires"
date: "September 20, 2021"
output:
  xaringan::moon_reader:
    css: mckpam.css
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
 
---

# Analysis

- Open `1-3-mock-analysis.Rmd`

- This is taken from `The Carpentries` [`R for Reproducible Scientific Analysis`](https://swcarpentry.github.io/r-novice-gapminder/) repository.

- This project uses the `Gapminder` dataset for some simple analysis

- The [Gapminder project](https://www.gapminder.org/data/) has collected data from countries around the world that look at communication, economic, education, environment, health, infrastructure, population, society, and work in each country.


---

# Practice

- We will take a mock analysis and create a different outputs for it.

- We will build the following:

  - R notebook
  - html document
  - slides
  - RShiny app
  - Dashboard (try if you have time)

---

# Output

-	Documents
- Presentations
- Notebooks
-	Slide Presentations
- Dashboards
- Interactive Documents
- Other
  - Websites
  - Blogs
---

# Documents

- html_notebook - Interactive R Notebooks
- html_document - HTML document w/ Bootstrap CSS
- pdf_document - PDF document (via LaTeX template)
- word_document - Microsoft Word document (docx)
- odt_document - OpenDocument Text document
- rtf_document - Rich Text Format document
- md_document - Markdown document (various flavors)

---

# Outlines and Links

# Outline
* [Introduction](#intro)
* [Section 1](#sec1)
    + [Subsection 1](#sec1_sub1)
    + [Subsection 2](#sec1_sub2)   

## Introduction {#intro}
…

## Section 1 {#sec1}
…

### Subsection 1 {#sec1_sub1}
…

### Subsection 2 {#sec1_sub2}

---

# Presentations (slides)

- ioslides_presentation - HTML presentation with ioslides
- revealjs::revealjs_presentation - HTML presentation with reveal.js
- slidy_presentation - HTML presentation with W3C Slidy
- beamer_presentation - PDF presentation with LaTeX Beamer
- powerpoint_presentation: PowerPoint presentation

---

# Notebooks

- Rmarkdown enables you to build an analysis notebook called an R notebook

---

# Interactive Presentation

- RShiny

---

# Dashboards
- flexdashboard (in `other` folder)

---
# `flexdashboard` Overview

- Flexdashboards allow us to publish related content in R that is more organized for consumers of your work

- First we set up how we want to organize the layout of our page (rows, columns, input sidebar, etc.)

- Next, we use our R Markdown skills to inject the content for each of these sections

- If we want to have dynamic content (served through R Shiny), we need to do the following:
  - Capture user input(s)
  - Send input(s) to the appropriate location to render output via the reactive() function.
  - The function checks for any changes and updates accordingly
